---
replicaCount: 1

image:
  repository: some.repo
  tag: latest
  port: 8080                # Просто порт, потом если что можно будет поменять
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 400m       # Возможно нужно будет больше поставить, но в задании не сказано насколько больше CPU прилоежние потребляет при деплое, в дальнейшем это следует определить в ходе работы и уменьшить значение (или провести нагрузочное тестирование, желательно чтобы оно было одним из этапов CI/CD пайплайна)

replicaCount: 4
